# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c
sudo: required
dist: trusty
script: ./travis-tool.sh run_tests

before_install:
  - sudo apt-get update
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_deps

install:
  - ./travis-tool.sh install_deps
  
env:
   global:
     - R_LIBS="http://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - BOOTSTRAP_LATEX=""
     - NOT_CRAN="true"

r_github_packages:
 - USGS-R/smwrData
 - USGS-R/smwrBase
 - USGS-R/smwrGraphs
 - USGS-R/smwrStats
script: ./travis-tool.sh run_tests

after_script:
  - "./travis-tool.sh dump_logs"

notifications:
  email:
    on_success: change
    on_failure: change